### ISSUE TITLE
error with TSM and the consecutive face-crops length(defalut 11) 

### ISSUE THREAD

**Issue by huangxhao** [SRA2/SPELL#1]
Hi, I am trying to run your code, and I use my own dataset for training and testing, but I found some possible bugs in 
`models_stage1_tsm.py`.

1. I guess this '3' should be '3*clip_length', where 'clip_length' is the length of face-crops
![image](https://user-images.githubusercontent.com/51191510/195589646-eda316fb-1d8c-49ff-971f-2ddf6a96018d.png)

2. This rgb_stack_size shoude be equal with clip_length?
![image](https://user-images.githubusercontent.com/51191510/195590488-46b9b66e-c73e-4ba5-a71a-51ed85e3c019.png)

When rgb_stack_size is 11 (default), the program always throws an exception here
![image](https://user-images.githubusercontent.com/51191510/195591741-f037a4f7-7b44-47bd-b0c8-e4c819ebfbc1.png)
I have no idea to solve it, if you can help me, I'd really appreciate it.

**Comment by kylemin** [comment]
Hi,

No, that is not a bug. It should remain as 3.
You don't need to change anything.
Please make sure that your input sizes are the same as below:
v: (B, rgb_stack_size, 3, H_v, W_v)
a: (B, 1, H_a, W_a)

Thank you,
Kyle

**Comment by huangxhao** [comment]
Thanks! After resizing the input, it works well.
