### ISSUE TITLE
Google Drive links has been invalid

### ISSUE THREAD

**Issue by sdqdlgj** [SRA2/SPELL#12]
Hi Kyle,

Thanks for your very nice code with excellent results!
Unfortunately, the Google Drive links has been invalid.
I wonder if you can provide the Google Drive links in the README again？

Thank you very much!

**Comment by kylemin** [comment]
Hi,

We are currently working on this problem. I'll get back to you soon.

Thank you,
Kyle

**Comment by kylemin** [comment]
@sdqdlgj The issue has been solved. Please try the new links and let me know if they do not work properly.
