### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by victorbcyang** [SRA2/SPELL#2]
Hi,

Thank you for sharing this amazing project. I am able to follow your instruction to train a model. I am also interested in running inference on my own data. Could you please share the visualization code as well?

Thank you very much!

**Comment by kylemin** [comment]
Hi,

Technically, the inference code is already included in `train_val.py`([link](https://github.com/SRA2/SPELL/blob/main/train_val.py#L130)).
Do you need a script that has only this function, e.g. `eval_only.py`?

We do not have a plan to publicize our visualization code in the near future, but we want to note here that we used matplotlib.pyplot (`Rectangle()` and `text()` of it, specifically).

Thank you,
Kyle
