### ISSUE TITLE
Requirements file

### ISSUE THREAD

**Issue by AdhamKhalifa** [SRA2/SPELL#3]
Hello,

Thank you so much for sharing these files. Could you please share the requirements list? (Including python, PyTorch, other dependencies, etc). Thank you!

**Comment by kylemin** [comment]
Hi,

This codebase requires only PyTorch and PyG (other dependencies will be installed automatically when you install these two libraries).
We confirmed that it is compatible with multiple different versions of Python, PyTorch, PyG. 

Please follow the official installation instruction of PyG: [link](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html)

Thank you,
Kyle
